#!/usr/bin/env bash
#ping IP adresss 5 times
count=5
address=$1
#for ((i=1; i<=$num_pings; i++)); do
if [ -z "$address" ];then 
	echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
else
		ping -c 5 $address
fi
#done
