#!/usr/bin/env bash
#advanced process 

while true
do 
		echo "$$" > /var/run/myscript.pid
		echo "To infinity and beyond"
		trap "echo I hate the kill command" SIGTERM
		trap "echo Y U no love me?!" SIGINT
		trap "rm /var/run/myscript.pid" SIGQUIT SIGTERM
done
