#!/usr/bin/env bash
#basic until loop 

counter=1
while [ $counter -le 100 ]
do
	
	if [[ $counter%3 == 0 && $counter%5 == 0 ]]; then
		echo "FizzBuzz"
	else
		if [[ $counter%3 == 0 ]]; then
			echo "Fizz"
		else 
		if [[ $counter%5 == 0 ]]; then
			echo "Buzz"
		else	
			echo $counter
		fi
		fi 
	fi
	((counter++))
done
