#!/usr/bin/env bash
#basic for loop

re="school"
for file in *
do
	if [ -e "$re" ]; then 
		echo "school file exists"
		if [ -s "$re" ]; then
			echo "school file is not empty"
		else
			echo "school file is empty"
		fi
		if [ -f "$re" ]; then
                        echo "school is a regular file"
		elif [ -d "$re" ]; then
			break
		fi
		break
	elif [ ! -e "$re" ]; then
	 	echo "school file does not exist"
		break
	fi
done
