#!/usr/bin/env bash
#change home IP
cp /etc/hosts ~/hosts.new
sed -i 's/127.0.0.1/127.0.0.2/' ~/hosts.new
sed -i -e 'a8.8.8.8 facebook.com' ~/hosts.new
cp -f ~/hosts.new /etc/hosts
#cp /etc/hosts ~/hosts.new
#sed -i -e 'a8.8.8.8 facebook.com' ~/hosts.new
#cp -f ~/hosts.new /etc/hosts
